import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/components/providers/convex-provider";
import { ConvexHttpClient } from "convex/browser";
import Navbar from "@/components/Navbar/page";
import Footer from "@/components/Footer/Footer";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <div className="flex flex-col">
            {/* <Navbar /> */}
            <Toaster position="bottom-center"/>
            {children}
            {/* <Footer /> */}
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
